# Generated by Django 4.1.2 on 2022-10-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=30)),
                ('sinopsis', models.TextField()),
                ('author', models.CharField(max_length=20)),
            ],
        ),
    ]
